name: goals_diary
description: Goals Diary

publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Architecture
  flutter_bloc: ^7.0.0
  injectable: ^1.4.0
  get_it: ^7.1.3
  provider: ^5.0.0

  # Data
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  # Design
  cupertino_icons: ^1.0.2

  # Utils
  freezed_annotation: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  injectable_generator: ^1.4.0
  flutter_launcher_icons: ^0.9.0
  freezed: ^0.14.1+3
  hive_generator: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

assets:
  - assets/images/

flutter_intl:
  enabled: true
  arb_dir: lib/src/common/l10n
