name: goals_diary
description: Goals Diary

publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Architecture
  flutter_bloc: ^6.1.1
  injectable: ^1.0.7
  get_it: ^5.0.6
  provider: ^4.3.3

  # Data
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  hive_generator: ^0.8.2

  # Design
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  injectable_generator: ^1.0.7
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

assets:
  - assets/images/

flutter_intl:
  enabled: true
  arb_dir: lib/common/l10n
